spring:
  application:
    name: Things
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    port: '587'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          smartthings:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${BASEURL}/oauth/callback
            scope: r:devices:* w:devices:* x:devices:*
        provider:
          smartthings:
            authorization-uri: https://api.smartthings.com/oauth/authorize
            token-uri: https://api.smartthings.com/oauth/token

jwt:
  accessTokenKey: ${JWT_ACCESS_TOKEN_KEY}
  accessTokenExpires: 1800000
  refreshTokenKey: ${JWT_REFRESH_TOKEN_KEY}
  refreshTokenExpires: 259200000